### ISSUE TITLE
Shooter - First Pass

### ISSUE THREAD

**Issue by pordonj** [frc1675/frc1675-2024#11]
# Task Description

Take the Shooter subsystem from design to a first-pass implementation in the robot project

## Prerequisites

- [x] frc1675/frc1675-2024-general#13

## Actions Needed

- [x] Using the high level design, determine what `Command`s will need to be performed by the `Subsystem`
- [x] Review with Josh/Jake/Michael that all required Commands are identified
- [x] Make a new branch for your code (ask Josh, Jake or Michael for help)
- [x] Write the Subsystem class. Refer to last years robot code or the code you worked on during preseason for examples. Do not code to specific sensors for now  (ask Josh, Jake or Michael for help and why)
- [x] Write the Commands that use your Subsystem.
- [x] Assign the Commands to controller inputs so that you can test their operation using the simulator.
- [x] Use the simulator to test each of your commands
- [x] Push your branch to github and make a pull request for review  (ask Josh, Jake or Michael for help)
- [x] Complete review iterations - if you change your code during review, test again before pushing.

## Resources

- High level design: https://github.com/frc1675/frc1675-2024-general/blob/main/design/V1/requirements.md
- Initial class diagram: https://github.com/frc1675/frc1675-2024-general/blob/main/design/V1/class-diagram.md
- Last year's code: https://github.com/frc1675/frc1675-2023

## Completion Criteria

- [x] Code is tested via simulator
- [x] Code is merged into main branch
