### ISSUE TITLE
LED Subsystem

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#21]
# Task Description
LED Subsystem and commands are created with at least four distinct patterns available. 
## Prerequisites
None

## Actions Needed
- [x] LED Subsystem created
- [x] Command created to interface with LED subsystem
- [x] LEDs are tested in simulator
- [x] LEDs are wired
- [x] LEDS are tested on robot 

## Completion Criteria
- [x] LEDs tested on robot and behave correctly
- [x] A new PR is merged to main

**Comment by python-42** [comment]
#26

**Comment by python-42** [comment]
#26
