### ISSUE TITLE
Test swerve functionality on new chassis

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#22]
# Task Description
Basic swerve functionality is tested and confirmed on new chassis.

## Prerequisites
New chassis is available for use.

## Actions Needed
- [x] All swerve functionality is tested
- [x] Non-working functionality is fixed
Repeat these steps until all functionality is achieved as outlined in swerve requirements document. 

## Completion Criteria
- [x] Basic swerve functionality is working on robot
