### ISSUE TITLE
Create UndertakerIO implementations

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#25]
# Task Description

Real and Sim arm IO implementations are created and tested. 

## Prerequisites

- [x] #9

## Actions Needed
 We have decided that for ease of simulation and testing we will be taking a different approach. Each subsystem will have a IO interface which declares the necessary methods for interacting with the given subsystem. This interface will then have two implementations: a real implementation, which interfaces with the hardware, and a simulated implementation, which mocks the actual hardware. If these concepts do not make sense, ask for help. 

- [x] Interface created
- [x] Real implementation
- [ ] Sim implementation

## Completion Criteria
- [x] Implementations created and integrated
- [x] Sim implementation successfully tested in simulator
- [x] Real implementation successfully tested on robot
