### ISSUE TITLE
Create advanced autonomous routines

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#28]
# Task Description
Create some baseline auto routines. 

## Prerequisites
Need to have access to all of the major robot subsystems.
- [x] #9 
- [x] #10
- [x] #11

Preferably 
- [x] #21 

Also should complete more basic autos first
- [x] #35 
- [x] #36 
- [x] #37 

## Actions Needed
Need to create some autonomous routines for us to use at the first competition. 
 - [ ] Determine our goals for our first iteration autonomous. 
 - [ ] Create autonomous routines based on these goals

Pathing should be done via PathPlanner. "Named Commands" can be referenced when creating an auto in PathPlanner. These commands are then registered in `AutoGenerator` . These commands should be fairly high level, so that we do not have to register many commands. 

### Example
Command PickUpNote; 
- Moves the undertaker in to position
- Runs the motors on undertaker
- Moves robot in to note position
- Runs the feeder motors

### Non Example
Command intake:
- Runs the undertaker motors

Command AcceptNote
- Runs the feeder motors

etc.

The final registered command should probably be a composition of the commands described in the non example, but non example commands should not be directly called by autonomous routines. 

## Completion Criteria
- [ ] We have multiple autonomous routines which start from different start positions
- [ ] Routines are tested on the robot and function properly
- [ ] Routines meet the goals we determined for first iteration autonomous.

**Comment by python-42** [comment]
To clarify the purpose of this issue, this basically represents "better autos" aside from #35, #36 and #37
