### ISSUE TITLE
Advanced AutoOps tasks

### ISSUE THREAD

**Issue by jherrmann06** [frc1675/frc1675-2024#29]
# Task Description
Determine tasks for advanced automated routines which are supposed to run in TeleOp. (AutoOps)

## Prerequisites
- [x] #9 
- [x] #10
- [x] #11

Preferably 
- [x] #21 

## Actions Needed

Create automated routines which are supposed to run in TeleOp. These routines should be one high-level robot action. Example: ScoreNoteHigh would move a short distance to a scoring position, set arm and shooter states appropriately, then shoot the note. These routines can be triggered by the driver or operator, but do not necessarily have to be. 

- [ ] Determine appropriate AutoOps to create
- [ ] Create issues for each AutoOp

More advanced ideas
- Robot drives to a scoring position and scores on button press (See SpeakerScore.java)
- Undertaker runs on its own in certain regions of the field if we dont have a note (might not be super useful but we will see)
- Robot speed is smoothly decreased in certain regions of the field or when manipulators are in certain states

## Completion Criteria

- [ ] Some appropriate ideas AutoOps are created 
- [ ] AutoOps are safe enough to use 
- [ ] Drivers approve of AutoOps
- [ ] Mentors approve
- [ ] New Github issues are created to guide further work
