### ISSUE TITLE
Subsystem Integration

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#31]
# Task Description
All subsystems are properly integrated with each other. 

## Prerequisites
- [x] #9 
- [x] #10 
- [x] #11 

## Actions Needed
- [x] Commands are created with represent high level robot actions. These commands call multiple subsystems
Example: Shoot command will begin spinning up the motors, then move the arm to the correct position, then wait for the motors to be at the correct speed, then roll the indexer to move the note in to the shooter.
- [x] Subsystems are prevented from completing certain counterproductive or unsafe actions based on the state of other subsystems
Example: The undertaker will refuse to intake a note while the arm is out of the home position. If the undertaker were to intake the note, it would fall in to the bellypan and we do not want this. 

## Completion Criteria
- [x] All changed are tested and work properly
- [x] New branch is review and merged in to main
