### ISSUE TITLE
Design first pass robot controls

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#32]
# Task Description

Sensible default robot controls for both driver and operator are designed and implemented in the `RobotContainer`.

## Prerequisites
- [x] #11 
- [x] #10 
- [x] #9 

## Actions Needed
- [x] Sensible default controls are identified and documented.
- [x] These controls are implemented in robot container

Note that we should start using the `XboxControllerCommand` (docs [here](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj2/command/button/CommandXboxController.html)) objects instead of the `Joystick` objects. These are much more efficient to work with since they abstract away some of the verbose code we currently have in `RobotContainer`. 

## Completion Criteria
- [x] Controls created and tested on robot
- [x] Mentor and Jake (because I was on drive team before) sign off on controls.

**Comment by python-42** [comment]
Todo for Feb. 29th:

- [ ] Driver: Robot translation
- [ ] Driver: Robot rotation
- [ ] Driver: Shoot on right trigger
- [ ] Operator: Move arm to home on right trigger
- [ ] Operator: Move arm to amp on left trigger
- [ ] Operator: Disable intake on Y
- [ ] Operator: Re-enable intake on A
- [ ] Automatic: Scale shoot speed for amp score
- [ ] Automatic: Disable intake with note
- [ ] Automatic: Disable intake with arm movement
- [ ] Automatic: Scale drivetrain on arm movement
