### ISSUE TITLE
Create competiton dashboard

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#33]
# Task Description

Competition driver dashboard is created to show drivers critical information during the match. 

## Prerequisites
- [x] #31 

## Actions Needed

- [ ] Identify what information the drivers need to know. 
- [ ] Place this information on shuffleboard
- [ ] Test layout in simulator
- [ ] Test on robot if needed

Remember that drivers are usually completely focused on the robot, so information should only be absoutely critical information and should be very easy to understand at a glance (i.e. mostly or entirely booleans)

Starter information (not a complete list)
 * Note loaded?
 * Shooter wheels ready to fire?
 * **x** subsystem working properly? 

## Completion Criteria
- [ ] Shuffleboard layout has been fixed in code 
- [ ] Shuffleboard tested on robot 
- [ ] Selected information and layout are reviewed by drivers (if selected) or somebody else and signed off
