### ISSUE TITLE
Test limelight pose estimate

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#34]
# Task Description
Test existing limelight pose update on robot. 

## Prerequisites
- [x] Limelight is mounted on robot

## Actions Needed
- [ ] Verify that limelight is seeing april tags
- [ ] Verify that limelight is calculating correct pose
- [ ] Verify that drive pose estimate is being updated when it should be. 

## Completion Criteria
- [ ] Above conditions meet during on robot test
- [ ] Any code changes reviewed
