### ISSUE TITLE
Autonmous Mode: Drive away

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#35]
# Task Description

Create autonomous routines that drive away from the starting position. 

## Prerequisites
Working drivetrain

## Actions Needed
- [ ] Create auto routine
- [ ] Test on robot 

## Completion Criteria
- [ ] Multiple starting positons exist
- [ ] Auto routine works consistently

**Comment by python-42** [comment]
We will never actually use this so I will not make it. Components exist to make it on the fly if it becomes necessary.
