### ISSUE TITLE
Autonomous Mode: Score preloaded

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#36]
# Task Description

Create autonomous modes which score the preloaded note and drive away. 

## Prerequisites
 - [x] #35 

## Actions Needed
Create autonomous routine which
 - [x] Scores the preloaded note in the speaker 
 - [x] Drives away 
 - [ ] Can do so from multiple starting positions
 - [ ] Test on robot

## Completion Criteria

- [ ] Autonomous routine works from multiple starting positions
- [ ] Autonomous routine works consistently
