### ISSUE TITLE
Autonomous: Score 2

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#37]
# Task Description

Create autonomous routines which score the preloaded piece, pick up another, score it, and drive away. 

## Prerequisites
- [x] #36 

## Actions Needed
Create autunomous mode which
- [ ] Scores the preloaded piece
- [ ] Collects a new one
- [ ] Scores the new one
- [ ] Drives away

The autonomous mode should also 
- [ ] Have more than one valid starting point
- [ ] Be able to collect different notes for its single intaken note

## Completion Criteria
- [ ] Autonomous mode is successfully tested on robot 
- [ ] Autonomous mode is reliable
