### ISSUE TITLE
Subsystem Unit Testing Coverage

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#39]
# Task Description

Write all unit tests for subsystem logic

## Prerequisites

- [ ] #15 
- [ ] #14 
- [ ] #9 

## Actions Needed

- [ ] Determine what aspects of each subsystem need unit tests
- [ ] Write unit tests for Shooter
- [ ] Write unit tests for Arm
- [ ] Write unit tests for Undertaker

Code change for the subsystem should be as minimal as possible. However, it will likely be useful and likely necessary to create a new implementation of the IO interface for each subsystem which is only for testing. 

## Completion Criteria
- [ ] Every subsystem has unit tests
- [ ] All unit tests are passing
