### ISSUE TITLE
Code Quality Fix

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#40]
# Task Description

Review all existing code for style and naming conventions.

## Prerequisites

None, but it could be better to wait until most code is finished and merged

## Actions Needed

- [ ] Agree on a style guide
- [ ] Adapt all existing code to match this style guide.
- [ ] Create a way to enforce this style going forward (see editor config for a starting point)

## Completion Criteria

- [ ] All code matches in style
