### ISSUE TITLE
AutoOps: Create Observer Pattern for drive pose

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#41]
# Task Description

Create Observer Pattern to use for future AutoOps

## Prerequisites
None

## Actions Needed

 - [x] Come up with a better name 
 - [x] Create observer pattern impl. in drive sub
 - [x] Test with example command

## Completion Criteria

- [x] Command can subscribe to be scheduled when the drivetrain pose enters a certain area
- [x] Good separation of responsibilities is maintained (the drivetrain subsystem doesn't know too much)
