### ISSUE TITLE
AutoOps: Region based spinup

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#42]
# Task Description

Spin up the shooter motors to speed when robot enters a certain region of the field

## Prerequisites

- [ ] #41 
- [ ] #11 

## Actions Needed

- [ ] Command is created to spin up shooter motors when the robot enters a certain field region
- [ ] Command is scheduled appropriately
- [ ] Shooter motors are set back to zero when robot leaves area
- [ ] Shooter motors are set back to zero when shot (?)

## Completion Criteria

 - [ ] Command works properly in simulator
 - [ ] Command covers entire process, such as what to do after note is shot and what to do if robot leaves the area with or without shooting
