### ISSUE TITLE
AutoOps: Shooter angle adjuster

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#43]
# Task Description

Automatically move arm to correct angle in time to shoot from different places

**This is not a high priority issue!** 
## Prerequisites

- [ ] #41 
- [ ] #10

## Actions Needed

 - [ ] Command created which moves the arm to the correct angle based pose right before shooting
 - [ ] Command registered to observer pattern
 - [ ] Command tested in simulator

## Completion Criteria

- [ ] Command is tested in sim
- [ ] Command is tested on robot and works consistently.
