### ISSUE TITLE
Mitigate Failure - Undertaker

### ISSUE THREAD

**Issue by NoahWeishan** [frc1675/frc1675-2024#44]
# Task Description

Implement and test ways to mitigate possible failures for the Undertaker subsystem.

## Prerequisites

- [x] #9 

## Actions Needed
Mitigate following problems
- [ ] Roller can't turn (we think it should)

## Completion Criteria

- [ ] Tested on robot and simulator
- [ ] Approved by mentor or senior team member

## Case
Case: Current Limit Reached [CLR]
How can we tell? Current goes above an acceptable level (empirically determine acceptable level)
How to mitigate?: 1. Stop commanding if Current limit

Problem: Roller can't turn (we think it should)
What could cause: Axle damaged, Note jammed
How can we tell?: See CLR
How to mitigate?: See CLR, Possibly unjam by going other way
