### ISSUE TITLE
Integrate LED subsystem

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#45]
# Task Description

Integrate LED subsystem into important commands to give drivers important feedback during match.

## Prerequisites
- [x] #31

## Actions Needed

- [ ] Actions which the drivers want to know about determined
- [ ] Distinct color codes selected and documented
- [ ] Color codes are triggered when actions determined above occur
- [ ] (Optional) Create team color based idle animation which the robot displays while not doing anything (i.e. before matches)

## Completion Criteria

 - [ ] LED status tested in simulator
 - [ ] LED status tested on robot
 - [ ] All the colors look cool

**Comment by python-42** [comment]
#71
