### ISSUE TITLE
Mitigate Failure - Arm

### ISSUE THREAD

**Issue by NoahWeishan** [frc1675/frc1675-2024#46]
# Task Description

Implement and test ways to mitigate possible failures for the Arm subsystem.

## Prerequisites

- [x] #10 

## Actions Needed
Mitigate following problems
- [ ] Arm can't move (we think it should)
- [ ] Arm is moving (we didn't tell it to)
- [ ] Throughbore encoder stops working
- [ ] Home switch is hit but arm isn't home

## Completion Criteria

- [ ] Tested on robot and simulator
- [ ] Approved by mentor or senior team member

## Case
Case: Current Limit Reached [CLR]
How can we tell? Current goes above an acceptable level (empirically determine acceptable level)
How to mitigate?: 1. Stop commanding if Current limit

Problem: Arm can't move (we think it should)
What could cause: Note in the way
How can we tell?: See CLR
How to mitigate?: See CLR

Problem: Arm is moving (we didn't tell it to)
What could cause: Hostile intrusion
How can we tell?: See CLR
How to mitigate?: See CLR

Problem: Throughbore encoder stops working
what could cause: disconnected / damaged encoder
How can we tell?: Throughbore isn't changing but internal encoder is
How to mitigate?: 
  * Just give up (never move) (no preserved functionality guaranteed)
  * Try to use internal encoder (could be inaccurate, need to try) (preserve speaker and amp scoring)
  * Go down "slowly" until home switch hit (preserve speaker scoring)

Problem: Home switch is hit but arm isn't home
What could cause: Hostile intrusion, home switch damaged or disconnected
How can we tell?: home switch hit and arm angle outside acceptable range (switch defaults to true when disconnected)
How to mitigate?
 * Just give up (never move) (no preserved functionality guaranteed)
 * Try to continue using encoder (could be risky when going from some angle to home) (preserve speaker and amp scoring)
 * Go back to home and never move again (preserve speaker scoring)

**Comment by python-42** [comment]
Value to time ratio is not worth it for this item
