### ISSUE TITLE
Mitigate Failure - Shooter

### ISSUE THREAD

**Issue by NoahWeishan** [frc1675/frc1675-2024#47]
# Task Description

Implement and test ways to mitigate possible failures for the Shooter subsystem.

## Prerequisites

- [x] #11 

## Actions Needed
Mitigate following problems
- [ ] Feeder roller(s) jammed
- [ ] Indexer False Positive (no note, but thinks there is)
- [ ] Indexer False Negative (thinks there is no note but has one)
- [ ] Shooter roller isn't moving (we think it should)

## Completion Criteria

- [ ] Tested on robot and simulator
- [ ] Approved by mentor or senior team member

## Case
Case: Current Limit Reached [CLR]
How can we tell? Current goes above an acceptable level (empirically determine acceptable level)
How to mitigate?: 1. Stop commanding if Current limit

Problem: Feeder roller(s) jammed
What could cause: Axle damaged, Note jammed
How can we tell?: See CLR
How to mitigate?: See CLR, Possibly unjam by going other way

Problem: Indexer False Positive (no note, but thinks there is)
What could cause: Foreign object, hostile intrusion, Sensor damage/moved, Arena lighting vs shop
How can we tell?: (possibly) shape of signal, distance returned was ever out of acceptable range
How to mitigate:
  * Just give up (never shoot again)
  * Manual control option (set of code to swap to if sensor doesn't work period / is broken)
  * Dynamic or triggered manual override (manual override during match)
  * Possibly detect a note entering undertake by current spike, then intake/index for some set amount of time

Problem: Indexer False Negative (thinks there is no note but has one)
What could cause: Sensor damage/moved
How can we tell?: (possibly) detect current spike in feeder and didn't see note after x time, distance returned was ever out of acceptable range
How to mitigate:
  * Just give up (never shoot again)
  * Manual control option (set of code to swap to if sensor doesn't work period / is broken)
  * Dynamic or triggered manual override (manual override during match)
  * Possibly detect a note entering undertake by current spike, then intake/index for some set amount of time

Problem: Shooter roller isn't moving (we think it should)
What could cause: Note jammed, Belt disconnected, 
How can we tell: See CLR (current would go up if jammed, Other shooter current would go up if one stops working)
How to mitigate: See CLR

**Comment by python-42** [comment]
Value to time ratio is not worth it for this item
