### ISSUE TITLE
Unit Test Refactor

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#5]
# Task Description

Refactor existing code to include TestableSparkMax and unit tests. 

## Prerequisites
- [x] frc1675/frc1675-2024#6 

## Actions Needed

- All of the sparkmax objects in the repositories should be replaced with the TestableSparkMax interface
- Unit tests are written for every subsystem. Unit tests test basic method for as many methods as require it (everything but basic getters and setters). 

## Completion Criteria
- [ ] SparkMax objects are replaced with TestableSparkMax throughout codebase
- [ ] Every subsystem has a test class associated with it
- [ ] Tests cover all necessary code and pass

**Comment by python-42** [comment]
Opted to take a different approach.
