### ISSUE TITLE
Logging to USB

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#57]
# Task Description
Figure out how to make roboRIO logs go to an attached USB.

## Prerequisites
None

## Actions Needed
- [x] Figure out how to get logs to be written to an attached USB rather than the internal storage
- [ ] Delete the logs which currently exist on the roboRIO. This can be accomplished with the log downloader. 

## Completion Criteria
- [x] Logs are written to the USB when attached.
- [ ] Existing logs are deleted to free up roboRIO space. 
- [x] Explanation of fix is documented.

**Comment by python-42** [comment]
Last I checked logs were not being written to the USB when attached. Logs are being written to the internal storage though.
