### ISSUE TITLE
Add command to spit note

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#59]
# Task Description

We need to create and bind a command which spits out the note. 

## Prerequisites
- [ ] #31 

## Actions Needed

- [ ] Create command 
- [ ] Bind command to button
- [ ] Test 

This command should raise the arm slightly, the run the indexer and undertaker motors backwards per Adams suggestion. This should prevent any further jamming while ensuring that notes from both the indexer and undertaker are ejected. 

## Completion Criteria

- [ ] Command is tested in the simulator
- [ ] Command is tested on robot 
- [ ] Command successfully ejects note(s) consistently

**Comment by python-42** [comment]
#62
