### ISSUE TITLE
Update testable sparkmax as necessary

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#6]
# Task Description
Update the TestableSparkMax interface and implementations to match current requirements.

## Prerequisites
- [ ] Reach a point in the season where we believe that unit testing is beneficial and easily implemented.

## Actions Needed
The TestableSparkMax interface and classes (frc1675/frc1675-2024#1) likely need to be updated to match current robot subsystem usage of sparkmaxes. Once they are updated, their implementation should be tested as outlined below. 

## Completion Criteria
- [ ] Interface has all functions required by the subsystems.
- [ ] Example test case is written and test cases which use testable sparkmax pass
- [ ] SparkMax is tested on robot

**Comment by python-42** [comment]
Opted to take a different approach.
