### ISSUE TITLE
LaserCAN POC

### ISSUE THREAD

**Issue by pordonj** [frc1675/frc1675-2024#7]
# Task Description

Develop proof-of-concept (POC) code for use in testing and familiarization with the sensor.

Work with design team to ensure that if we choose to use this sensor it can be mounted in the robot.

## Prerequisites

- [x] 2024 robot project available

## Actions Needed

- Work with electrical team to understand proper wiring and use of the sensor.
- Read documentation to understand proper configuration of the sensor.
- Write proof of concept code for using the LaserCAN and push it to a branch.
- Show ability to use as a rangefinder and how accurately we can tell range (on order of feet? inches?)

## Completion Criteria

- [x] POC code is written
- [x] Sensor is attached to a robot and used
- [x] General limits of use are established and documented
- [x] Design team knows how they will mount this sensor in the robot if needed

**Comment by python-42** [comment]
#13 
 The LaserCAN values are accurate within about 1.5 meters
 There is some small sensory jitter, so we will have to use range when checking on targets
