### ISSUE TITLE
Arm current limit

### ISSUE THREAD

**Issue by python-42** [frc1675/frc1675-2024#80]
# Task Description
Add a current limit to the arm

## Prerequisites
None

## Actions Needed

- [ ] Empirically determine a good current limit for the arm
- [ ] Add current limit
- [ ] Test that functionality is preserved

## Completion Criteria

- [ ] Code tested on robot and functionality is preserved
